### ISSUE TITLE
Implement RFC0038: SBOM

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/web-servers#45]
To implement [Paketo RFC0038](https://github.com/paketo-buildpacks/rfcs/blob/932d89a970bea06c002496dbd6c7e3812ccab788/text/0038-cdx-syft-sbom.md), this buildpack (and the implementation buildpacks inside) will need to move from storing SBOM information in layer metadata to storing it in files that the CNB lifecycle can manipulate during the build. The RFC outlines what these files are and what they should contain. 

This issue serves as a meta-issue for work required to complete this work for the Web Servers language family. This will require (link Github issues as they are created):

* [x] https://github.com/paketo-buildpacks/httpd/issues/311
* [x] https://github.com/paketo-buildpacks/nginx/issues/369

**Comment by ForestEckhardt** [comment]
I believe that this track of work is over. Is there anything else that needs to be done?

**Comment by ForestEckhardt** [comment]
Closing this as all of the criteria has been fulfilled.
