### ISSUE TITLE
Implement RFC0004: Support "zero-configuration" build processes

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/web-servers#57]
[RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/web-servers/0004-zero-config.md)

## Summary

The NGINX and HTTPD buildpacks within the Web Servers language-family should
provide a "zero-configuration" option whereby they generate a very simple
configuration so that the buildpack user does not need to.

## Implementation Issues

- [x] https://github.com/paketo-buildpacks/httpd/issues/298
- [x] https://github.com/paketo-buildpacks/httpd/issues/299
- [x] https://github.com/paketo-buildpacks/httpd/issues/300
- [x] https://github.com/paketo-buildpacks/httpd/issues/301
- [x] https://github.com/paketo-buildpacks/httpd/issues/302
- [x] https://github.com/paketo-buildpacks/nginx/issues/353
- [x] https://github.com/paketo-buildpacks/nginx/issues/354
- [x] https://github.com/paketo-buildpacks/nginx/issues/355
- [x] https://github.com/paketo-buildpacks/nginx/issues/356
- [x] https://github.com/paketo-buildpacks/nginx/issues/357

**Comment by fg-j** [comment]
@paketo-buildpacks/web-servers-maintainers Seems like this is done. Any reason to keep this issue open?

**Comment by thitch97** [comment]
I don't think so. Closing.
