### ISSUE TITLE
Support Jammy Jellyfish

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/web-servers#85]
## Describe the Enhancement

Ultimately, we want to be able to build NGINX/HTTPD web servers on top of the Paketo Jammy stacks. Currently, builds fail because buildpacks like `nginx` don't have the Jammy stack listed in their supported stacks.

## Possible Solution

- Update `buildpack.toml` and dependencies to add `io.buildpacks.stacks.jammy` as a compatible stack
- (If necessary) Recompile installed dependencies to work on Jammy 
- Add some integration tests that test the buildpack against Jammy

## Motivation

Part of https://github.com/paketo-buildpacks/builder-jammy-base/issues/1

**Comment by fg-j** [comment]
HI there. I think I'm missing some context – what's blocking this?

**Comment by TisVictress** [comment]
> HI there. I think I'm missing some context – what's blocking this?

This is waiting on the new dependency workflow changes to properly compile webservers dependencies.
